### ISSUE TITLE
Chrome and autoHeight shows 1px height image when refresh page

### ISSUE THREAD

**Issue by jdmoliner** [smashingboxes/OwlCarousel2#538]
Hi,

When I'm using chrome and refresh the page, the image is only 1px height.

You can check the bug here. Only when refresh the page and chrome:

http://cultura.burjassot.org/teatro/la-asombrosa-historia-de-mr-snow/

**Comment by joeyjoejoejr** [comment]
Can someone verify that this is still an issue?

**Comment by KennethAshley** [comment]
Please upgrade to the newest version of Owl Carousel, released today, and re-open this issue if it persists.

**Comment by rodrigoAbril** [comment]
I can still replicate this issue 
http://codepen.io/anon/pen/oXRMKQ

**Comment by greg5green** [comment]
You need to use `$(window).load` instead of `$(document).ready` if you want to use autoHeight with images. `ready` fires before images are loaded, so autoHeight is working as it should by setting the height to be 0 or 1 pixels tall. Another option would be to set up the carousel on `ready`, but trigger a `refresh.owl.carousel` on `load` so that the carousel knows to re-check the element's height.

**Comment by dallanlee** [comment]
This thread seems a little divided. Can anyone confirm that using `$(window).load` is the proper/best way to initiate the the owl slider with images and autoHeight? [The autoHeight demo](https://owlcarousel2.github.io/OwlCarousel2/demos/autoheight.html) uses `<div>`s with set heights in CSS and not responsive heights from images like many developers are intending to do. It makes sense that the demo is able to use `$(document).ready` without issue. Using `$(window).load` with images works for me but there is a FOUC.

**Comment by designifyer** [comment]
I had this issue in 2 cases:
1. When I initialize owl carousel on a .owl-carousel class (you should use an id or another class)
`<div class="owl-carousel"></div>`
2. If I use a class of .slide on my items. You should use .item or any other class.
`<div id="some_ID">
<div class="slide"><img src="some_image" alt=""></div>
</div>`
Hope this helps.

**Comment by tanmuhittin** [comment]
`$(window).load` works for me too

**Comment by tovarart** [comment]
confirm - $(window).load - works for me as well
Thanks!

**Comment by powellian** [comment]
I just had this error and can also confirm `window.onload` works.
Thanks for the tip.

**Comment by bobyhrp** [comment]
The issue still persists. 
With the newest jQuery you can't call `$(window).on('load')` inside `$(document).ready()` - and sometimes there's no workaround for that, depending on your code architecture.

Here's a simple way:

```
var $owl = $('#element').owlCarousel(...);

$owl.find('img').each(function() {
	$(this).on('load', function() {
		$owl.trigger('refresh.owl.carousel');
	});
});
```

You can try optimizing the code, so that `refresh.owl.carousel` doesn't fire that many times. It still works though.
 I tried calling in when the last image loads, but it didn't really work.
