### ISSUE TITLE
Development?

### ISSUE THREAD

**Issue by wpexplorer** [smashingboxes/OwlCarousel2#658]
Has development stopped on this project?

**Comment by VladShcherbin** [comment]
the last commit was in August, lots of issues and some pr, beta for a year, no answers from the author

you really think it didn't stop ? =/

**Comment by pronkman** [comment]
I was also wondering about this for a while now – I tend to agree with VladShcherbin considering the frequency of commits before and after Aug. Hopefully I'm wrong :/

**Comment by visualcookie** [comment]
Oh, and don't forget the Twitter-Account. Pretty much inactive. :-1:

**Comment by VladShcherbin** [comment]
Don't give me wrong, I found the owl carousel about a year ago and liked it a lot, told my friends to use it whenever they need carousel/slider because it was cool. That time, the 2 version was already in beta and I came here probably a year after and boom - it is still the same beta version. So, I was surprised, but downloaded to test it. I made it work, but there were some bugs and the project is inactive.

So, I switched to Slick JS - it can do the same things, easy to install, config, use and it is active.

It's a pity, such a great carousel died in beta. Don't know why the author abandoned it.

**Comment by orosznyet** [comment]
@VladShcherbin Same for me, I recommended this great (potentially even better with 2.0) carousel but after 5-6 commit-free months It seems like Owl Carousel reached its end (I must agree). 

Slick.js looks interesting, but that landing page... could use a hand. Either way I'll give it a try.

**Comment by wpexplorer** [comment]
slick js looks great, thanks for the share!

Light Slider is also pretty amazing, I've been using that one lately - http://sachinchoolur.github.io/lightslider/

**Comment by joeyjoejoejr** [comment]
Closing as duplicate.
