### ISSUE TITLE
Bug in chrome with Loop

### ISSUE THREAD

**Issue by epiblue** [smashingboxes/OwlCarousel2#780]
Here's the example:
http://www.golulo.es/es/

The boxes witch fades (COLECCION JUNIOR) with 2 images with the loop, on the 3rd time in blinks/gliches.

Is there a fix? Or what may be causing it?

Thanks,

**Comment by igoradamenko** [comment]
Try to add `z-index: 1` to `.owl-item` (via #772)

**Comment by greg5green** [comment]
Using `rewind: true` instead of `loop: true` should fix your problem in the newest version, beta 3. (It appears you are using a pretty old version of the Owl Carousel 2 on that site, so you'll need to upgrade. Or else, you can try using `navRewind: true`)

If you still have this issue after upgrading, please open a new pull request and document the bug as described in https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports. Thanks.
