### ISSUE TITLE
iPhone, iPad Issue: Owl carousel not working in an iframe when view with safari.

### ISSUE THREAD

**Issue by sanvuthy** [smashingboxes/OwlCarousel2#811]
I have used Owl carousel recently. Everything is working fine in desktop browsers. But in iPad/iPhone safari it's not working fine with the iframe. The width of the iframe become wider base on owl-wrapper width.

Here is the example in codepen. I really need you help.

http://codepen.io/anon/pen/KppXgx

Thanks in advance.

**Comment by designcouch** [comment]
I'm experiencing this exact same issue. It's in a codepen embed on this page: http://www.designcouch.com/home/why/2015/05/19/ux-exercise-building-a-responsive-survey/

**Comment by greg5green** [comment]
@sanvuthy Your demo uses OwlCarousel 1, which is a separate project. You can find their issue tracker at https://github.com/OwlFonk/OwlCarousel/issues. You can also try with our newest version 2.0.0-beta.3 which seems to work in my limited testing.

@designcouch Your demo uses a quite pretty old beta version. I think it is fixed in the newest version, so try that (available on Bower or downloadable from http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip) and if it isn't resolved, please open a new issue.

Thanks!
