### ISSUE TITLE
Lazy load not working properly when 'items' is set to less than 2

### ISSUE THREAD

**Issue by alexvaxx** [smashingboxes/OwlCarousel2#820]
Hi there, I am trying to do an almost full page slider with lazy images.

I am setting my 'items' to 1.2 for instance, and this is where the trouble arises.

The lazyload loads the images for the current slide and for the previous slide but not for the next one.

Whenever i set items to more than 2, it works perfectly. But I need it to work with less than 2.

Here is a jsfiddle: http://jsfiddle.net/k3mvLs0k/

Would be great with some input on this issue, thanks!

**Comment by aleroy** [comment]
I believe the value of the `items` option was intended to be of type `integer`. You might have fewer issues if you use a whole number ... however, the real problem here is that you have the option: `center:true` ... change that `false` and you should work.

The logic behind the lazy loader is that it should defer loading until the image is in view. With `center:true` and `items < 2` it thinks the slide is only halfway into view ...so, it shouldn't load it yet.

    // line 1855
     n = (settings.center && Math.ceil(settings.items / 2) || settings.items),

**Comment by alexvaxx** [comment]
Aha, but the problem is that if I don't set center:true then i can't see the edges of the previous and the next images, which is the effect I want. With center:false I can only see the edges of the next, and not the previous as well.
With items set to 2.01 or anything else > 2 (not only integers) and with center:true, it will preload images that are only partly visible – it would be nice to have it work the same way with items set to < 2.

**Comment by aleroy** [comment]
@witrin's prefretch option should help you. Copy the code from [here](https://github.com/witrin/OwlCarousel2/blob/develop/src/js/owl.lazyload.js) and paste it over the lazyload section of your owl.carousel.js file.

You'll have to set the `lazyPrefetch` option to 2 or more.

**Comment by alexvaxx** [comment]
Perfect! That works. Thank you very much.

**Comment by aleroy** [comment]
Glad I could help .... that prefetch mod resolved an issue I was having as well. great stuff!

**Comment by iandonovan** [comment]
Thanks again, @aleroy
