### ISSUE TITLE
carousel elements blur after transition

### ISSUE THREAD

**Issue by Bogdanel** [smashingboxes/OwlCarousel2#848]
Hi there, 
On translate3d math to coordinates should be rounded to 0. If translate3d gets values like x.5 then elements in carousel gets blurred. 
So I added coordinate.toFixed(0) to fix this error in this section: 

Line: 1324 / owl.carousel.js
if (this.support3d) {
			this.dom.$stage.css({
				transform: 'translate3d(' + coordinate + 'px' + ',0px, 0px)',
				transition: (this.speed() / 1000) + 's'
			});
		}

**Comment by iandonovan** [comment]
I can't seem to find this line of code anymore, which makes sense, as this issue is more than three weeks old and we've recently released a [new version](http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip).

Can you do me a favor and try to reproduce this issue on that new release? I'll reopen this thread if it persists.
