### ISSUE TITLE
Stop carousel flicker

### ISSUE THREAD

**Issue by djhsecondnature** [smashingboxes/OwlCarousel2#910]
Is there a way to stop this brief flicker on load seen on this carousel?

http://rail.ricardo.com/

**Comment by greg5green** [comment]
I don't think this is anything inherent with the carousel but just the time it takes to download, parse, and render a website.

If you're referring to the text divs stacking up 4 deep before the carousel can invoke itself (I think you are?), you can add some css to hide those divs until the js runs to invoke the carousel. There's a bit of a risk with adding css to hide them, since your js could fail to load and then you'd only have 1/4 of the content (which you might not have if the js failed somehow anyways). I guess it depends which is more important to you. You could also probably move the js up to the head instead of at the footer where you have it now, but this certainly has its tradeoffs too.

With regards to the images, they are some pretty hefty file sized images so they'll take a minute to load. If you're concerned about the black background showing up before the image, you could try invoking the carousel on `$(window).load` instead of `$(document).ready`, but this would probably exacerbate the text div issue since you would be waiting even longer to invoke the carousel.

If there's a bug with the carousel that I'm not seeing here, please respond (and come up with a codepen illustrating the problem) and I'll reopen the issue.

If there isn't a bug here and you need further personal support, please use [Stack Overflow](http://stackoverflow.com/questions/tagged/owl-carousel)
