### ISSUE TITLE
Bug in the dot navigation

### ISSUE THREAD

**Issue by dbdev** [smashingboxes/OwlCarousel2#915]
When the number of the items is not a multiple of the number used in the option 'items' and the carousel is not a loop the last dot fails to highlight.

Here is an example http://codepen.io/anon/pen/XJENaQ

If one clicks the last DOT it slides to the last page but the dot doesn't get highlighted. If is gets changed to loop in the options than it works properly.

Please help anyone I've been dealing with this issue for long time but haven't managed to fix it.

**Comment by greg5green** [comment]
@dbdev This is fixed in the newest version of OwlCarousel2. You can grab it from http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip or bower!

I updated your pen to use the newest version just to double check it was fixed. Here's the updated version in case you were curious: http://codepen.io/anon/pen/QbQvxj

Thanks!

**Comment by greg5green** [comment]
Sorry, I posted a bad link to the newest version the other day. The correct URL for the zip download is http://smashingboxes.github.io/OwlCarousel2/download/owl.carousel.2.0.0-beta.3.zip
