### ISSUE TITLE
当元素个数少于一个时候，loop参数配置为true会报错

### ISSUE THREAD

**Issue by uncoder-** [smashingboxes/OwlCarousel2#917]
Is not a bug, but this can be done automatically judge it?   thanks

![image](https://cloud.githubusercontent.com/assets/8252008/8491691/66191584-2170-11e5-8850-a3da51ef7979.png)

**Comment by greg5green** [comment]
@uncoder- I'm not really sure what you're asking for here and can't read the title. Any chance you could clarify for us? Thanks!

**Comment by greg5green** [comment]
I just ran this through Google Translate. The title looks like "When the number of elements in less than one time, the parameters for the loop will complain".

I think this is fixed in our newest version @uncoder-. Can you try downloading the newest version from bower or http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip?

**Comment by uncoder-** [comment]
@greg5green  

haha ,my english is poor,but maybe try it.

when The Elements in the container just has one element  and  opts set "loop:true",it is error in the browser "console" that said   "Uncaught TypeError: Cannot read property 'clone' of undefined"   

sorry ,maybe you can understand?

**Comment by thirdender** [comment]
I think this has been fixed in the latest version. I created a [Codepen](http://codepen.io/thirdender/pen/pJLdaw/) with a single element and `loop: true` and it seems to be working.

**Comment by uncoder-** [comment]
@thirdender   yes ,  it's  working

**Comment by greg5green** [comment]
:)
