### ISSUE TITLE
URLhashListener issue with current slide

### ISSUE THREAD

**Issue by getandyjones** [smashingboxes/OwlCarousel2#918]
Hi,

I wanted to have a contents page, which allows the user to jump to the desired slide on click.
so i enabled the URLhashListener : true

Then the url of slide 1 is #1, slide 2 is #2 and so on..

But, if i am looking at domain.com/#1
and then the user flicks through the slides using drag, or using the prev/next buttons, and then clicks on #1 again - it doesn't ump back to slide 1.

This is actually present on the demo:
http://www.owlcarousel.owlgraphic.com/demos/urlhashnav.html

Click on #zero, then click the dots to cycle through the slides, then click #zero again - nothing happens.

Any ideas a way to get round this?

Thanks!
Andy

**Comment by getandyjones** [comment]
I think the idea would be for the url hash to update automatically when the slide changes, rather than on click? no idea how to do this though!

**Comment by thirdender** [comment]
Try with a more recent version of Owl Carousel. Commit 83e125877d923b3d55f20fd0f7befb015321f99a added code to update `window.location.hash` when the a slide is changed. This means dragging or clicking the dot navigation to go to slide 2 would change the hash to `#2`, and clicking any other link should take you to the appropriate slide.

I checked, and the copy of the Owl Carousel library used on the http://www.owlcarousel.owlgraphic.com/demos/urlhashnav.html demo page is older than this commit.

**Comment by greg5green** [comment]
@thirdender :+1:

@getandyjones This is fixed in the most recent version. You can get it from bower or download from http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip

The project changed hands a few months ago and we're [unfortunately] still in the process of changing over our docs to a different host. http://smashingboxes.github.io/OwlCarousel2/demos/urlhashnav.html has the most recently released code up there and doesn't have this problem.

**Comment by greg5green** [comment]
Sorry, a good url for download is http://smashingboxes.github.io/OwlCarousel2/download/owl.carousel.2.0.0-beta.3.zip, not the one I posted above :(

**Comment by getandyjones** [comment]
That' great - thanks!!!! :)
