### ISSUE TITLE
Owl v2 with Thumbnail Sync & Loop

### ISSUE THREAD

**Issue by fastnetwebdesign** [smashingboxes/OwlCarousel2#926]
Hi There

Re: Owl v2

We have used the following to sync main images with thumbnails:

https://github.com/smashingboxes/OwlCarousel2/issues/580#issuecomment-107319546

But, when adding in 'loop: true' to loop the main images & thumbnails, the carousel breaks.

Has anyone achieved this or is there any easy fix?

Thanks
Phil

**Comment by NPanayotov** [comment]
You can check this issue if it helps.
https://github.com/smashingboxes/OwlCarousel2/issues/923

**Comment by fastnetwebdesign** [comment]
Thank you NPanayotov

Is there a way to have the thumbnails slide also in sync, as there may be 30-40 images and we don't want them all shown - maybe just 4 or 6 thumbnails at a time - then sliding left as you scroll through.

Thanks
Phil

**Comment by NPanayotov** [comment]
Well, in order to do that you need to initialize a carousel for the thumbs as well, and here comes the problem when you initialize the carousel for the thumbs it changes the html structure and the dotsContainer no longer works. The thing that you can do that comes to my mind is to write a function for the callback onChanged: for example

```JS

var $thumbs = $('.thumbs owl-carousel');
$thumbs.owlCarousel({
items: 5,
dots: fasle
});

$('.slider .owl-carousel').owlCarousel({
items: 1,
onChanged: function (event) {
     var item = event.item.index; 
     $thumbs.trigger('to.owl.carousel', item, 500);
}
});

```

Please note that this will work only if you have loop disabled. Because it uses the index of the item and when you have loop enabled it clones the slides and messes up the index.

**Comment by daviddeutsch** [comment]
Check out this issue for a solution: [issues/1378 - Linked OwlCarousel instances](https://github.com/OwlCarousel2/OwlCarousel2/issues/1378)
