### ISSUE TITLE
Dynamically changing carousel options

### ISSUE THREAD

**Issue by andyexeter** [smashingboxes/OwlCarousel2#937]
There should be a way to dynamically change the current settings/options of a carousel.

For example, I have a carousel where each image has a "Tap to Zoom" button. When the button is tapped, I want to set `touchDrag` and `mouseDrag` to false so the user can drag around the zoomed image without the next or previous slide being dragged in and when the image is tapped they should both be set to true again.

Changing the setting on the element's owlCarousel data object has no effect e.g:

`$('#carousel').data('owlCarousel').settings.touchDrag = false;`
or
`$('#carousel').data('owlCarousel').options.touchDrag = false;`

There doesn't appear to be anything documented about it at http://www.owlcarousel.owlgraphic.com/docs/started-welcome.html either.

**Comment by greg5green** [comment]
Thanks for the idea here. It sounds like something interesting to add, but it isn't feasible at the moment. I'm going to close this, but will be adding the icebox tag because it is something we might like to implement in the future.

You might be able to get around your exact issue by setting up, when you zoom in, your own event listeners on the `touchstart`/`dragstart` events that prevents the event from bubbling up to the carousel's code.

Thanks!
