### ISSUE TITLE
Owl Carousel not displayed on iOS

### ISSUE THREAD

**Issue by FlorianBrinkmann** [smashingboxes/OwlCarousel2#946]
I have the following problem:

If I visit the page http://philipzintarra.de on iOS, the slider is not displayed. It works fine on Windows, Mac and Android ...

Is there a solution for that?

**Comment by greg5green** [comment]
Not real sure exactly what the issue is, but you are using a pretty old version of OwlCarousel2 and other carousels definitely work on iOS so I think it's a config issue rather than a bug. I'd recommend grabbing the newest version (from the download button on http://smashingboxes.github.io/OwlCarousel2/ or upgrading via bower).

If you still have issues after that, check [Stack Overflow](http://stackoverflow.com/questions/tagged/owl-carousel) for help or try to come up with a smaller test case on Codepen, jsfiddle, or jsbin that we can debug and open a new issue.

Thanks.

**Comment by FlorianBrinkmann** [comment]
Thanks for your hint with the new version. I have downloaded the script from http://www.owlcarousel.owlgraphic.com/ and thought this would be the official site.

The problem is solved, it was something with the CSS I used for displaying all stages on smaller screens. Now I use destroy.owl.carousel and it works fine :)
