### ISSUE TITLE
Grayscale effect

### ISSUE THREAD

**Issue by Andergraw** [smashingboxes/OwlCarousel2#956]
Maybe it is something we could do outside the box with grayscale plugin but, it would be awesome having this feature. You know, grayscale logos colored on hover or inverse.
Thanks!

**Comment by thirdender** [comment]
You could easily do this with CSS filters, as well as a few fallbacks for older browsers (see [Convert Images To Black And White With CSS](http://demosthenes.info/blog/532/Convert-Images-To-Black-And-White-With-CSS)).

**Comment by greg5green** [comment]
I don't see us adding this to the project since it's something that would be pretty easy to do with CSS for your specific content, but would be incredibly hard and complex to do well without being able to be specific about things. If you did come up with a good way to do it though and already implemented it for your own project, feel free to come up with a pull request that adds it as a separate add-on plugin and we'll think about merging it.
