### ISSUE TITLE
Autoplay + Pause on Hover + Stop Autoplay

### ISSUE THREAD

**Issue by apermo** [smashingboxes/OwlCarousel2#970]
If I setup a slider with the options: 

...
autoplay: true,
autoplayHoverPause: true,
...

and trigger "stop.owl.autoplay" later, the autoplay will stop as wanted.

So far everything as expected, now the problem:

If I hover the slider now, the slider triggers another stop, and if I move the mouse away, it triggers another start, so the autoplay starts over again.

**Comment by teej043** [comment]
There seem to be a bug around the autoplayHoverPause, even the autoplay triggerable events by attaching to "mouseover" and "mouseleave" doesn't work. The "autoplayHoverPause = true" only ever work once when page reloads, after that it won't work anymore.

**Comment by greg5green** [comment]
@apermo Your issue with hover starting autoplay again after it's been manually stopped was fixed with beta 3. [Test case](http://codepen.io/anon/pen/mJZJvq)

@teej043 In beta 3, `autoplayHoverPause` works after manually triggering `stop.owl.autoplay` and then `play.owl.autoplay` again. If this isn't what you're describing, please open another issue. [Test case](http://codepen.io/anon/pen/RPzPdj)
